# Generated by Django 4.1.2 on 2022-12-01 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_month', models.CharField(default='January', max_length=10)),
                ('start_day', models.CharField(default='1', max_length=10)),
                ('start_year', models.CharField(default='2022', max_length=10)),
                ('monthly_total', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=4), max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
