# Generated by Django 4.1.2 on 2022-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_day',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_month',
            field=models.CharField(default='January', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_year',
            field=models.CharField(default='2022', max_length=10),
        ),
    ]
