# Generated by Django 4.1.2 on 2022-12-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_subscription_date_subscription_start_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20),
        ),
    ]
